name: Discord Commits Notification

on:
  push:
    branches:
      - main

  uses: Sniddl/discord-commits@v1.6
  with:
    webhook: ${{ secrets.DISCORD_WEBHOOK }}
    template: "avatar-with-link"
    include-extras: true
