name: Discord Commits Notification

on:
  push:
    branches:
      - main  # ou ajuste aqui se a sua branch principal tiver outro nome

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Commits
        uses: appleboy/discord-commits@v1.0.0
        with:
          webhook_id: 1366121449575944395
          webhook_token: 0qgBaB1FX2YFb6fCPN7ENr99nt3PgXQDvSsxgOzOkpeoEJAEXxEbn4-EYufLnapDLyxP
