name: Discord

on:
  -push
jobs:
  discord:
    runs-on: ubuntu-latest
    staps:
      - uses: actions/checkout@v4
      - name: Run Discord Webhook
        user: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
