name: Continuous Integration

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      # Step para fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Step para enviar mensagem para o Discord usando a action
      - name: Run Discord Webhook
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
