name: Run Unit Tests

on:
  pull_request:
    branches:
      - main  # ou qualquer branch que você usar como principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de ter um arquivo requirements.txt com as dependências necessárias

      - name: Run tests
        run: |
          python -m unittest discover tests  # Assumindo que os testes estejam em uma pasta chamada "tests"
